# Auto-generated from brew.nix — run `brew bundle` to sync.
# Casks are macOS-only and omitted on Linux.

tap "derailed/k9s"
tap "hashicorp/tap"
tap "human37/open-wispr"
tap "modem-dev/tap"

brew "awscli"
brew "bat"
brew "fd"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "git-standup"
brew "helix"
brew "herdr"
brew "jq"
brew "k9s"
brew "kubecolor"
brew "kubectx"
brew "lazygit"
brew "libaacs"
brew "libpq"
brew "libtool"
brew "neovim"
brew "opencode"
brew "ossp-uuid"
brew "python-setuptools"
brew "uv"
brew "vault"
brew "zls"
brew "hunk"
brew "open-wispr"
