# Auto-generated from brew.nix — run `brew bundle` to sync.
# Casks are macOS-only and omitted on Linux.

brew "awscli"
brew "bat"
brew "fd"
brew "gh"
brew "git-filter-repo"
brew "git-lfs"
brew "git-standup"
brew "helix"
brew "herdr"
brew "jq"
brew "kubecolor"
brew "kubectx"
brew "lazygit"
brew "libaacs"
brew "libpq"
brew "libtool"
brew "neovim"
brew "opencode"
brew "python-setuptools"
brew "uv"
brew "zls"
