# Read by login shells - interactive terminals and non-interactive ones alike.
#
# nvm is loaded here and not in .zshrc on purpose: tools that start outside a
# terminal (PI WEB's LaunchAgents, for example) run through `zsh -lc` and would
# otherwise get a different node/npm than your terminal does.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" >/dev/null

# Docker Desktop's completion check (Settings -> "Configure shell completions")
# runs `zsh -lc` and looks for _docker in fpath. A login shell reads this file
# and that check is not interactive, so it never sees ~/.zshrc - and ~/.zshenv
# is nix-darwin's, which is why the FPATH line has to live here. Exported so
# non-login shells (tmux panes, zsh -c) inherit it too.
# The _docker file itself is generated by home.nix on every switch.
export FPATH="$HOME/.docker/completions:${FPATH:-}"
