# Read by login shells - interactive terminals and non-interactive ones alike.
#
# nvm is loaded here and not in .zshrc on purpose: tools that start outside a
# terminal (PI WEB's LaunchAgents, for example) run through `zsh -lc` and would
# otherwise get a different node/npm than your terminal does.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" >/dev/null

# Docker Desktop manages neither of these for us, and both belong in this file
# rather than in .zshrc for the same reason: a `zsh -lc` check (Docker Desktop's
# own completion check is one) reads .zshenv and .zprofile but not .zshrc, and
# .zshenv is nix-darwin's.
#
# ~/.docker/bin is only on PATH in environments that happen to inherit it, so a
# terminal started from the Dock has no docker at all without this. Guarded, so a
# machine without Docker Desktop keeps a clean PATH.
[ -d "$HOME/.docker/bin" ] && export PATH="$HOME/.docker/bin:$PATH"
#
# Exported so non-login shells (tmux panes, zsh -c) inherit the completion too.
# The _docker file itself is generated by home.nix on every switch.
export FPATH="$HOME/.docker/completions:${FPATH:-}"
